/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
} from "../common";

export interface EventsInterface extends Interface {
  getEvent(nameOrSignatureOrTopic: "BridgeEvent"): EventFragment;
}

export namespace BridgeEventEvent {
  export type InputTuple = [
    brokerAddress: AddressLike,
    userAddress: BytesLike,
    chainId: BigNumberish,
    amount: BigNumberish,
    fee: BigNumberish,
    isEthFee: boolean
  ];
  export type OutputTuple = [
    brokerAddress: string,
    userAddress: string,
    chainId: bigint,
    amount: bigint,
    fee: bigint,
    isEthFee: boolean
  ];
  export interface OutputObject {
    brokerAddress: string;
    userAddress: string;
    chainId: bigint;
    amount: bigint;
    fee: bigint;
    isEthFee: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Events extends BaseContract {
  connect(runner?: ContractRunner | null): Events;
  waitForDeployment(): Promise<this>;

  interface: EventsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getEvent(
    key: "BridgeEvent"
  ): TypedContractEvent<
    BridgeEventEvent.InputTuple,
    BridgeEventEvent.OutputTuple,
    BridgeEventEvent.OutputObject
  >;

  filters: {
    "BridgeEvent(address,bytes32,uint8,uint128,uint128,bool)": TypedContractEvent<
      BridgeEventEvent.InputTuple,
      BridgeEventEvent.OutputTuple,
      BridgeEventEvent.OutputObject
    >;
    BridgeEvent: TypedContractEvent<
      BridgeEventEvent.InputTuple,
      BridgeEventEvent.OutputTuple,
      BridgeEventEvent.OutputObject
    >;
  };
}
