/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IZkJumpETH,
  IZkJumpETHInterface,
} from "../../contracts/IZkJumpETH";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "brokerAddress",
        type: "address",
      },
    ],
    name: "receiveFee",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IZkJumpETH__factory {
  static readonly abi = _abi;
  static createInterface(): IZkJumpETHInterface {
    return new Interface(_abi) as IZkJumpETHInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IZkJumpETH {
    return new Contract(address, _abi, runner) as unknown as IZkJumpETH;
  }
}
