/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC5267__factory } from "./IERC5267__factory";
export { IERC5313__factory } from "./IERC5313__factory";
